name: Reusable Release Workflow
on:
  workflow_call:
    secrets:
      DOCKER_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: |
          # Reemplazaar 'TU_USUARIO_DOCKER' por tu nombre de usuario real de Docker Hub
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u bapp86 --password-stdin
